# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UICollectionView-Custom' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for UICollectionView-Custom
pod ‘SDWebImage’

end
